"""
Create an offense‑vs‑defense EPA scatter plot for NFL teams.

This script reads a CSV file produced by ``scripts.fetch_epa`` containing
per‑team offensive and defensive EPA per play.  It then creates a
scatter plot where each team is represented by either its logo (if
available in ``assets/logos/<team>.png``) or a coloured square with the
team abbreviation.  Two reference lines are drawn at the league‑average
offensive and defensive EPA values.  The resulting chart is saved
to ``epa_scatter.png`` in the repository root.

Use ``--invert-y`` when lower defensive EPA values indicate better performance,
so the axis direction matches your preferred interpretation.

Example usage::

    python -m scripts.plot_epa_scatter --season 2025 --week "Weeks 1–6" --invert-y
"""

import argparse
from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
import pandas as pd
from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]

try:
    # When executed as: python -m scripts.plot_epa_scatter
    from .plot_team_color_squares import NFL_TEAM_COLORS, pick_text_color
except ImportError:  # pragma: no cover
    try:
        from plot_team_color_squares import NFL_TEAM_COLORS, pick_text_color
    except ImportError:  # pragma: no cover
        import sys
        sys.path.insert(0, str(REPO_ROOT))
        from plot_team_color_squares import NFL_TEAM_COLORS, pick_text_color


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot offense vs defense EPA scatter for NFL teams.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--season",
        type=int,
        required=True,
        help="Season year matching the CSV generated by scripts.fetch_epa",
    )
    parser.add_argument(
        "--week",
        type=str,
        default=None,
        help="Optional subtitle describing the week range (e.g., 'Weeks 1–6')",
    )
    parser.add_argument(
        "--invert-y",
        action="store_true",
        default=False,
        help="Invert the defensive EPA axis (useful when lower values are better).",
    )
    parser.add_argument(
        "--logos-dir",
        type=str,
        default="assets/logos",
        help="Directory containing team logo PNG files named <team>.png",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="epa_scatter.png",
        help="File path to save the resulting PNG chart",
    )
    return parser.parse_args()


def load_team_epa(season: int) -> pd.DataFrame:
    """
    Load per‑team EPA data from CSV.

    Parameters
    ----------
    season : int
        Season year used to construct the CSV filename.

    Returns
    -------
    pd.DataFrame
        Team EPA metrics indexed by team.
    """
    csv_path = REPO_ROOT / "data" / f"team_epa_{season}.csv"
    if not csv_path.exists():
        raise FileNotFoundError(
            f"EPA data file not found: {csv_path}. Did you run scripts.fetch_epa first?"
        )
    df = pd.read_csv(csv_path)

    # Handle legacy CSVs that may include a numeric index column
    if "team" not in df.columns:
        unnamed = [c for c in df.columns if str(c).lower().startswith("unnamed")]
        if unnamed:
            df = df.rename(columns={unnamed[0]: "team"})

    # Normalize common column-name variants
    rename_map = {}
    if "off_epa_per_play" in df.columns and "EPA_off_per_play" not in df.columns:
        rename_map["off_epa_per_play"] = "EPA_off_per_play"
    if "def_epa_per_play" in df.columns and "EPA_def_per_play" not in df.columns:
        rename_map["def_epa_per_play"] = "EPA_def_per_play"
    if rename_map:
        df = df.rename(columns=rename_map)

    required = {"team", "EPA_off_per_play", "EPA_def_per_play"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"{csv_path} is missing required columns: {', '.join(sorted(missing))}. "
            f"Found columns: {', '.join(df.columns.astype(str))}"
        )

    df["team"] = df["team"].astype(str).str.strip().str.upper()
    df["EPA_off_per_play"] = pd.to_numeric(df["EPA_off_per_play"], errors="coerce")
    df["EPA_def_per_play"] = pd.to_numeric(df["EPA_def_per_play"], errors="coerce")
    return df.set_index("team")


def add_team_marker(
    ax: plt.Axes,
    x: float,
    y: float,
    team: str,
    logos_dir: Path,
) -> None:
    """
    Draw a team marker at the specified coordinates.

    If a logo PNG exists in ``logos_dir/<team>.png``, it is placed at the
    coordinate.  Otherwise a coloured square with the team's abbreviation
    is drawn using primary/secondary colours defined in
    ``NFL_TEAM_COLORS``.

    Parameters
    ----------
    ax : plt.Axes
        Matplotlib axes on which to draw.
    x, y : float
        Coordinates for the centre of the marker.
    team : str
        Three‑letter team abbreviation (e.g., ``'BUF'``).
    logos_dir : pathlib.Path
        Directory containing team logos named ``<team>.png``.
    """
    logo_path = logos_dir / f"{team}.png"
    if logo_path.exists():
        try:
            img = Image.open(logo_path)
            # Use a consistent scaling factor relative to the figure size
            imagebox = OffsetImage(img, zoom=0.5)
            ab = AnnotationBbox(imagebox, (x, y), frameon=False, pad=0.0)
            ax.add_artist(ab)
            return
        except Exception:
            # Fall back to coloured square if loading fails
            pass

    # Fallback: coloured square with team abbreviation
    colours = NFL_TEAM_COLORS.get(team, {"primary": "#777777", "secondary": "#FFFFFF"})
    primary = colours["primary"]
    secondary = colours["secondary"]
    text_color = pick_text_color(primary, secondary)
    # Draw square marker
    ax.scatter(
        [x],
        [y],
        marker="s",
        s=400,  # adjust size for readability
        color=primary,
        edgecolors="black",
        linewidths=0.5,
        zorder=3,
    )
    ax.text(
        x,
        y,
        team,
        ha="center",
        va="center",
        fontsize=8,
        fontweight="bold",
        color=text_color,
        zorder=4,
    )


def plot_scatter(df: pd.DataFrame, week_label: Optional[str], invert_y: bool, logos_dir: Path, output_path: Path, season: int) -> None:
    """
    Create and save the offense vs defence scatter plot.

    Parameters
    ----------
    df : pd.DataFrame
        Dataframe indexed by team containing 'EPA_off_per_play' and 'EPA_def_per_play' columns.
    week_label : str, optional
        Subtitle describing the week range (e.g., "Weeks 1–6").  If None, a default
        'Season to date' subtitle is used.
    invert_y : bool
        If True, invert the y‑axis direction (useful when lower defensive values are better).
    logos_dir : pathlib.Path
        Directory containing team logo PNG files.
    output_path : pathlib.Path
        Where to write the PNG file.
    season : int
        Season year for labelling.
    """
    df = df.dropna(subset=["EPA_off_per_play", "EPA_def_per_play"])
    if df.empty:
        raise ValueError("No rows to plot after dropping missing EPA values.")

    # Compute league averages
    x_vals = df["EPA_off_per_play"]
    y_vals = df["EPA_def_per_play"]
    x_avg = x_vals.mean()
    y_avg = y_vals.mean()

    fig, ax = plt.subplots(figsize=(10, 6))

    # Plot each team
    for team, row in df.iterrows():
        add_team_marker(ax, row["EPA_off_per_play"], row["EPA_def_per_play"], team, logos_dir)

    # Draw reference lines at league averages
    ax.axvline(x_avg, color="grey", linestyle="--", linewidth=1.0, zorder=1)
    ax.axhline(y_avg, color="grey", linestyle="--", linewidth=1.0, zorder=1)

    # Label axes
    ax.set_xlabel("Offense EPA per play (higher = better offense)")
    y_label = "Defense EPA per play"
    if invert_y:
        y_label += " (axis inverted)"
    ax.set_ylabel(y_label)

    # Title and subtitle
    title = f"NFL Team Efficiency (EPA/play), {season}"
    subtitle = week_label if week_label else "Season to date"
    ax.set_title(title + "\n" + subtitle, pad=14)

    # Improve layout
    ax.grid(False)
    # Give some margins so markers aren't clipped
    padding_x = (x_vals.max() - x_vals.min()) * 0.1
    padding_y = (y_vals.max() - y_vals.min()) * 0.1
    ax.set_xlim(x_vals.min() - padding_x, x_vals.max() + padding_x)
    y_min = y_vals.min() - padding_y
    y_max = y_vals.max() + padding_y
    if invert_y:
        ax.set_ylim(y_max, y_min)
    else:
        ax.set_ylim(y_min, y_max)

    plt.tight_layout()
    fig.savefig(output_path, dpi=200)
    print(f"Saved scatter plot to {output_path}")


def main() -> None:
    args = parse_args()
    season = args.season
    week_label = args.week
    invert_y = args.invert_y
    logos_dir = Path(args.logos_dir)
    if not logos_dir.is_absolute():
        logos_dir = REPO_ROOT / logos_dir

    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = REPO_ROOT / output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)

    df = load_team_epa(season)
    plot_scatter(df, week_label, invert_y, logos_dir, output_path, season)


if __name__ == "__main__":
    main()
